name : First Workflow
on : workflow_dispatch
jobs :
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name : Print greetings
        run  : echo "Hello World!"
      - name : Print Goodbye
       
        run: |
          id
          echo "Home: $HOME"
          echo "Shell: $SHELL"

